title: Ziqian Xia
description: Welcome to Ziqian Xia's Personal Page.
show_downloads: true
color:
  header: "#FFFFFF"
  gradient_left: "#30E8BF"
  gradient_right: "#FF8235"
  
baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lorepirri.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
