title: Ziqian Xia
description: This website is outdated.
show_downloads: true
  
baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://Ziqian-xia.github.io" # change this to the base hostname & protocol for your site


google_analytics: G-Q7WG8NN5F8

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty



plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
